# Generated by Django 5.2.15 on 2026-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_actor_full_name'),
        ),
    ]
