# Generated by Django 5.2.15 on 2026-07-14 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_actor_unique_actor_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name may contain only letters, hyphens, and apostrophes.', regex="^[^\\W\\d_]+(?:['-][^\\W\\d_]+)*$")]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name may contain only letters, hyphens, and apostrophes.', regex="^[^\\W\\d_]+(?:['-][^\\W\\d_]+)*$")]),
        ),
    ]
