# Generated by Django 5.2.15 on 2026-07-15 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_alter_actor_first_name_alter_actor_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Genre name may contain only letters, spaces, and hyphens.', regex='^[^\\W\\d_]+(?:[ -][^\\W\\d_]+)*$')]),
        ),
    ]
