# Generated by Django 5.2.15 on 2026-07-16 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_alter_genre_options_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Title contains invalid characters.', regex='^[\\w\\s\'\\":;,.!?()&-]+$')]),
        ),
    ]
