# Generated by Django 5.2.15 on 2026-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_alter_play_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(),
        ),
    ]
