# Generated by Django 5.2.15 on 2026-07-18 10:37

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_alter_play_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actor',
            name='unique_actor_full_name',
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Last name may contain only letters, spaces, hyphens, and apostrophes.', regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Genre name may contain only letters, spaces, and hyphens.', regex='^[^\\W\\d_]+(?:[ -][^\\W\\d_]+)*$')]),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Title may contain only letters and single spaces.', regex='^[^\\W\\d_]+(?: [^\\W\\d_]+)*$')]),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='unique_actor_full_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_genre_name_ci'),
        ),
    ]
