# Generated by Django 5.2.15 on 2026-07-18 10:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_remove_actor_unique_actor_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actor',
            name='unique_actor_full_name_ci',
        ),
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_genre_name_ci',
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='unique_actor_full_name'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_genre_name'),
        ),
    ]
