# Generated by Django 5.2.15 on 2026-07-18 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_remove_actor_unique_actor_full_name_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrehalls',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Theatre hall name may contain only letters, spaces, and hyphens.', regex="^[^\\W\\d_]+(?:['-][^\\W\\d_]+)*$")]),
        ),
        migrations.AlterField(
            model_name='theatrehalls',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='theatrehalls',
            name='seats_in_rows',
            field=models.PositiveIntegerField(),
        ),
    ]
