# Generated by Django 5.2.15 on 2026-07-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_alter_theatrehalls_name_alter_theatrehalls_rows_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatrehalls',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
    ]
