# Generated by Django 5.2.15 on 2026-07-18 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_rename_seats_in_rows_theatrehalls_seats_in_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrehalls',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Theatre hall name may contain only letters, spaces, and hyphens.', regex='^[^\\W\\d_]+(?: [^\\W\\d_]+)*$')]),
        ),
    ]
