# Generated by Django 5.2.15 on 2026-07-18 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_alter_theatrehalls_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrehalls',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Theatre hall name may contain only letters, spaces, and hyphens.', regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")]),
        ),
    ]
