# Generated by Django 5.2.15 on 2026-07-18 12:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_alter_theatrehalls_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Theatre hall name may contain only letters, spaces, and hyphens.', regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")])),
                ('rows', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_in_row', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_theatre_hall_name')],
            },
        ),
        migrations.AlterField(
            model_name='performance',
            name='theatre_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theatre.theatrehall'),
        ),
        migrations.DeleteModel(
            name='TheatreHalls',
        ),
    ]
