# Generated by Django 5.2.15 on 2026-07-18 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0013_theatrehall_alter_performance_theatre_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrehall',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Theatre hall name may contain only letters, spaces, hyphens and apostrophes.', regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")]),
        ),
    ]
