# Generated by Django 5.2.15 on 2026-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0014_alter_theatrehall_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-show_time']},
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('play', 'theatre_hall'), name='unique_hall_performance'),
        ),
    ]
