# Generated by Django 5.2.15 on 2026-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0015_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performance',
            name='unique_hall_performance',
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('theatre_hall', 'show_time'), name='unique_hall_performance'),
        ),
    ]
