# Generated by Django 5.2.15 on 2026-07-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0016_remove_performance_unique_hall_performance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['show_time']},
        ),
    ]
