# Generated by Django 5.2.15 on 2026-07-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0018_alter_ticket_row_alter_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='theatre.performance'),
        ),
    ]
