# Generated by Django 5.2.15 on 2026-07-21 15:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0019_alter_ticket_performance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='play',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_play_title'),
        ),
    ]
